[package]
name = "riru-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
typed-jni = { git = "https://github.com/Kr328/typed-jni-rs.git", default-features = false }
